# -*- coding: utf-8 -*-
"""A generated font: shared [common] metrics plus one or more texture pages.

Both generators (compose, render) emit this shape, and `write` turns it into
the .ini + .png files StepMania expects.
"""
import os

PAGE_ORDER_KEY = "name"


def new_spec(src_cell, common, source):
    return {"src_cell": src_cell, "common": dict(common),
            "pages": [], "source": source, "missing": []}


def add_page(spec, name, image, cols, rows, chars, widths):
    spec["pages"].append({"name": name, "image": image, "cols": cols,
                          "rows": rows, "chars": chars, "widths": widths})


def _page_filename(font_name, page, cols, rows, res):
    tag = "" if page == "main" else " [%s]" % page
    return "%s%s %dx%d (res %dx%d).png" % (font_name, tag, cols, rows, res[0], res[1])


def ini_text(spec, font_name):
    sw, sh = spec["src_cell"]
    L = ["# Generated by fontpatch.py - do not hand-edit, it is rewritten on install.",
         "# Glyph source: %s" % spec["source"], "#"]
    for note in spec.get("notes", []):
        L.append("# %s" % note)
    L.append("")
    L.append("[common]")
    for k, v in spec["common"].items():
        L.append("%s=%s" % (k, v))
    for page in spec["pages"]:
        L.append("")
        L.append("[%s]" % page["name"])
        cols = page["cols"]
        for r in range(page["rows"]):
            chunk = "".join(page["chars"][r * cols:(r + 1) * cols])
            if chunk:
                # a literal '=' or a leading '#' would confuse the ini parser;
                # none of the scripts we emit contain them, but be explicit
                L.append("Line %-3d=%s" % (r, chunk))
        if page["widths"]:
            L.append("")
            L += ["%d=%d" % (k, v) for k, v in sorted(page["widths"].items())]
    return "\r\n".join(L) + "\r\n"


def write(dirpath, font_name, spec):
    """Write <font_name>.ini plus a png per page. Returns the paths written."""
    sw, sh = spec["src_cell"]
    written = []
    keep = set()
    for page in spec["pages"]:
        res = (sw * page["cols"], sh * page["rows"])
        fn = _page_filename(font_name, page["name"], page["cols"], page["rows"], res)
        keep.add(fn)
        p = os.path.join(dirpath, fn)
        page["image"].save(p)
        written.append(p)
    # drop stale pages from an earlier run with different geometry
    for fn in os.listdir(dirpath):
        if fn.startswith(font_name) and fn.endswith(".png") and fn not in keep:
            os.remove(os.path.join(dirpath, fn))
    ini = os.path.join(dirpath, font_name + ".ini")
    open(ini, "wb").write(ini_text(spec, font_name).encode("utf-8"))
    written.append(ini)
    return written


def glyph_count(spec):
    return sum(len(p["chars"]) for p in spec["pages"])
